In [104]:
import pandas as pd

%matplotlib inline

In [207]:
df=pd.read_csv('2019.csv')
keywords = [' ON ', 'SAINSBURYS', 'WAGAMAMA', 'CO-OP', 'COSTA']
keywords = [' ON ', '\*', '/', 'LTD',' PO ', ' BC', ' STORES ', ' REDHILL', ' MORTGAGE ', ' CO ', ' CONNEC', ' PYMTS ', ' FINANCI    ', ' PLC ', ' CAPITAL ', ' LIMITED ', ' MEM ', ' MIA ', ' NDDS ', ' PL ']
tidy(df, keywords)
#tidy(df, [' ON ', 'SAINSBURYS', 'WAGAMAMA', 'CO-OP', 'COSTA'])
#df['MMO'] = res[0]
#df
df['Memo'] = df['Memo'].str.strip()
df.Memo.unique()
df[df.Su]

,Date,Account,Amount,Subcategory,Memo
0,13/09/2019,20-26-46 83746836,-18.99,DIRECTDEBIT,THE GYM
1,13/09/2019,20-26-46 83746836,-50.00,FT,JULIA BASS
2,12/09/2019,20-26-46 83746836,-9.30,PAYMENT,SAINSBURYS S
3,12/09/2019,20-26-46 83746836,-3.00,PAYMENT,WH SMITH TRAVEL
4,12/09/2019,20-26-46 83746836,-8.99,PAYMENT,ITUNES.COM
5,11/09/2019,20-26-46 83746836,-2.50,PAYMENT,Metrobus
6,11/09/2019,20-26-46 83746836,-50.00,CASH,LINK
7,11/09/2019,20-26-46 83746836,-100.00,PAYMENT,SLIPSHOE ST DENTAL
8,11/09/2019,20-26-46 83746836,-7.99,PAYMENT,Audible.co.uk
9,10/09/2019,20-26-46 83746836,-0.90,PAYMENT,CO-OP GROUP FOOD
10,10/09/2019,20-26-46 83746836,-101.32,PAYMENT,W M MORRISONS.COM
11,10/09/2019,20-26-46 83746836,-7.99,PAYMENT,NOWTV.COM
12,10/09/2019,20-26-46 83746836,-3.24,PAYMENT,MILK&amp;MORE
13,10/09/2019,20-26-46 83746836,-2.30,PAYMENT,TWO MANY COOKS
14,09/09/2019,20-26-46 83746836,288.45,FT,204981 13823431 OPTIONAL FT
15,09/09/2019,20-26-46 83746836,-82.00,FT,FLUTE LESSONS MT15043377 FT
16,09/09/2019,20-26-46 83746836,-10.00,PAYMENT,CLAIRE&#039;S ACCESSORI
17,09/09/2019,20-26-46 83746836,-7.20,PAYMENT,COSTA COFFEE
18,09/09/2019,20-26-46 83746836,-5.35,PAYMENT,MARKS&amp;SPENCER
19,09/09/2019,20-26-46 83746836,-3.00,PAYMENT,EAST SURREY HOSPIT
20,09/09/2019,20-26-46 83746836,-2.00,PAYMENT,POUNDLAND
21,09/09/2019,20-26-46 83746836,-28.00,PAYMENT,HOMEBASE
22,09/09/2019,20-26-46 83746836,-24.29,PAYMENT,SHOPIFY
23,09/09/2019,20-26-46 83746836,-2.70,PAYMENT,COSTA COFFEE
24,09/09/2019,20-26-46 83746836,-0.79,PAYMENT,ITUNES.COM
25,09/09/2019,20-26-46 83746836,-300.00,CASH,202397 07SEP 14.52
26,09/09/2019,20-26-46 83746836,-10.50,DIRECTDEBIT,NATIONAL TRUST
27,06/09/2019,20-26-46 83746836,119.31,FT,204981 63357538 SHOPIFY MAY-SEPT FT
28,06/09/2019,20-26-46 83746836,-65.00,FT,REIGATE DANCE COMP
29,06/09/2019,20-26-46 83746836,-250.00,PAYMENT,JOHN LEWIS
...,...,...,...,...,...
2027,04/01/2019,20-26-46 83746836,-2.85,PAYMENT,MILK&amp;MORE
2028,04/01/2019,20-26-46 83746836,-85.00,DIRECTDEBIT,SAINSBURYS BANK
2029,04/01/2019,20-26-46 83746836,-50.00,DIRECTDEBIT,HMRC
2030,03/01/2019,20-26-46 83746836,-5.95,PAYMENT,Amazon.co.uk
2031,03/01/2019,20-26-46 83746836,150.00,DIRECTDEP,309001 00042186 mam BGC
2032,03/01/2019,20-26-46 83746836,-27.50,PAYMENT,WAGAMAMA ROYAL FES
2033,03/01/2019,20-26-46 83746836,-7.00,PAYMENT,PUCCINOS
2034,03/01/2019,20-26-46 83746836,-6.35,PAYMENT,LEVY RESTAURANTS U
2035,03/01/2019,20-26-46 83746836,-4.00,PAYMENT,LEVY RESTAURANTS U
2036,03/01/2019,20-26-46 83746836,-19.71,PAYMENT,EAT
2037,03/01/2019,20-26-46 83746836,-16.50,PAYMENT,NEW SOUTHERN RAILW
2038,03/01/2019,20-26-46 83746836,-6.90,PAYMENT,INDIGO UK-GTR
2039,03/01/2019,20-26-46 83746836,-1.59,PAYMENT,GOOGLE
2040,03/01/2019,20-26-46 83746836,-210.00,REPEATPMT,ABBEY MASTERCARD C 5286897469256575 STO
2041,02/01/2019,20-26-46 83746836,-25.70,PAYMENT,NATIONAL TRUST
2042,02/01/2019,20-26-46 83746836,-500.00,FT,204676 93127729 MOBILE-CHANNEL FT
2043,02/01/2019,20-26-46 83746836,-50.00,PAYMENT,FIRST UTILITY 2006274 BBP
2044,02/01/2019,20-26-46 83746836,-2400.00,DIRECTDEBIT,SANTANDER
2045,02/01/2019,20-26-46 83746836,-20.83,DIRECTDEBIT,GREENWICH LEISURE AX0310034098 DDR
2046,02/01/2019,20-26-46 83746836,-46.00,DIRECTDEBIT,VIRGIN MEDIA
2047,02/01/2019,20-26-46 83746836,-25.37,DIRECTDEBIT,DVLA-YF06BSY 000000000014062300 DDR
2048,02/01/2019,20-26-46 83746836,-8.40,PAYMENT,AMZN Mktp UK
2049,02/01/2019,20-26-46 83746836,-7.99,PAYMENT,AMZN DIGITAL
2050,02/01/2019,20-26-46 83746836,-18.00,PAYMENT,TIMPSON INSIDE MOR
2051,02/01/2019,20-26-46 83746836,-9.20,PAYMENT,COSTA COFFEE
2052,02/01/2019,20-26-46 83746836,-3.95,PAYMENT,BETWEEN THE LINES
2053,02/01/2019,20-26-46 83746836,-29.70,PAYMENT,WWW.IKEA.COM
2054,02/01/2019,20-26-46 83746836,-79.36,PAYMENT,WM MORRISONS STORE
2055,02/01/2019,20-26-46 83746836,-47.00,PAYMENT,HOMEBASE
2056,02/01/2019,20-26-46 83746836,-40.00,PAYMENT,BETWEEN THE LINES

In [106]:
memo = df.Memo.str.split(pat=' ON ', n=1, expand=True)
df['Memo'] = memo[0]


df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
df['year'] = pd.DatetimeIndex(df['Date']).year
df['month'] = pd.DatetimeIndex(df['Date']).month

df=df[['year', 'month','Memo', 'Subcategory', 'Amount']]

In [100]:
dfg=df.groupby(['Memo', 'Subcategory','month'], as_index=False)['Amount'].sum().sort_values('month')#.sort_values(['Amount', 'month'])
dfg = dfg[dfg.Amount < 0]
dfg = dfg[dfg.Subcategory != 'DIRECTDEBIT']
dfg.head()

                                             Memo Subcategory  month  Amount
665  MORTONS               IRELAND                    PAYMENT      1   -7.47
510  HSBC                  403810REIGATE                 CASH      1  -50.00
520                         INDIGO UK-GTR             PAYMENT      1  -28.35
524                         INSIDE OUT HEALTH         PAYMENT      1  -37.95
529  ITUNES.COM/BILL       IRELAND                    PAYMENT      1   -9.78

In [179]:
def tidy(df, keywords):
    
    for kw in keywords:
        res = df.Memo.str.split(pat=kw, n=1, expand=True)
        df['Memo'] = res[0]
    return df